import { mkdir, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import ora from "ora";
import { print } from "../ui/print.js";

type AiTarget = "cursor" | "claude" | "copilot" | "generic";

const FAKEBASE_MDC_CONTENT = `---
description: Fakebase local dev platform rules for AI agents
globs: ["**/*.ts", "**/*.tsx"]
alwaysApply: true
---

# Fakebase Project Rules

This project uses **Fakebase** — a local-only, Supabase-shaped database for Next.js prototyping.

## Critical Rules

- **Never** import from \`@supabase/supabase-js\` in this project. Use \`@byronwade/adapter-memory\` or \`@byronwade/adapter-json\` instead.
- **Never** add Supabase environment variables (\`SUPABASE_URL\`, \`SUPABASE_ANON_KEY\`) to \`.env.local\`.
- Import the Fakebase client from \`lib/fakebase.ts\` using: \`import { fakebase } from "@/lib/fakebase"\`
- Data only persists locally in \`.fakebase/\` (gitignored). This is intentional.

## Schema

Schema is defined in \`fakebase/schema.ts\`. After changing schema:
1. Run \`fakebase migrate new <name>\` to generate a migration
2. Run \`fakebase types gen\` to update \`database.types.ts\`

## Available Commands

\`\`\`
fakebase dev              # Start local server
fakebase studio           # Open admin UI
fakebase migrate new      # Create migration
fakebase migrate apply    # Apply migrations
fakebase types gen        # Regenerate TypeScript types
fakebase seed run         # Insert seed data
fakebase doctor           # Health check
\`\`\`

## Client Usage

\`\`\`ts
import { fakebase } from "@/lib/fakebase";

// Query
const { data } = await fakebase.from("profiles").select("*");

// Insert
await fakebase.from("profiles").insert({ username: "alice", user_id: "..." });
\`\`\`
`;

const AGENTS_MD_CONTENT = `# AGENTS.md — AI Agent Instructions

This project uses **Fakebase** for local database development.

## What Is Fakebase?

Fakebase is a local-only, Supabase-shaped tool for Next.js prototypes. It provides the same API surface as Supabase but stores data locally in \`.fakebase/\` with no external services.

## Key Constraints

1. **No Supabase imports** — use \`@byronwade/*\` packages only
2. **No .env.local database URLs** — Fakebase needs no connection strings
3. **Schema changes** require regenerating migrations and types
4. **Data is ephemeral** — use \`fakebase snapshot save\` to persist state

## Project Structure

\`\`\`
fakebase/
  schema.ts         ← Table definitions (edit this)
  seeds/seed.ts     ← Seed data
  migrations/       ← Auto-generated SQL
  storage/          ← Local file storage
.fakebase/          ← Runtime data (gitignored)
lib/fakebase.ts     ← Import the client from here
database.types.ts   ← Auto-generated (run: fakebase types gen)
\`\`\`

## Development Workflow

\`\`\`bash
fakebase dev         # Start server
fakebase studio      # Admin UI
fakebase doctor      # Check health
\`\`\`
`;

const FAKEBASE_RULES_MD_CONTENT = `# fakebase.rules.md

Rules for working with this Fakebase project.

## DO

- Use \`fakebase/schema.ts\` to define tables
- Run \`fakebase migrate new\` after schema changes
- Run \`fakebase types gen\` to keep types in sync
- Use \`fakebase snapshot save/restore\` for test state

## DON'T

- Import \`@supabase/supabase-js\`
- Set \`DATABASE_URL\` or Supabase env vars
- Edit \`database.types.ts\` manually
- Commit \`.fakebase/\` (it's gitignored)
- Use Fakebase in production

## Migration to Real Supabase

When ready to move to production:
1. \`fakebase migrate export --supabase\` — exports SQL migrations
2. \`fakebase seed export\` — exports seed data
3. Set up real Supabase project and run the migrations
4. Swap \`lib/fakebase.ts\` for \`@supabase/supabase-js\` client
`;

const SCHEMA_SUMMARY_CONTENT = `# Schema Summary

Generated by \`fakebase ai init\`. Edit \`fakebase/schema.ts\` to update.

## Tables

### profiles

| Column       | Type        | Notes                     |
|--------------|-------------|---------------------------|
| id           | uuid        | Primary key, auto-gen     |
| user_id      | uuid        | Unique, FK to auth.users  |
| username     | text        | Required                  |
| full_name    | text        | Optional                  |
| avatar_url   | text        | Optional                  |
| website      | text        | Optional                  |
| updated_at   | timestamptz | Defaults to now()         |

RLS: enabled

## Relationships

- \`profiles.user_id\` → \`auth.users.id\` (1:1)
`;

const COMPATIBILITY_SUMMARY_CONTENT = `# Fakebase ↔ Supabase Compatibility

Generated by \`fakebase ai init\`.

## Supported (EXACT)

- \`select()\`, \`insert()\`, \`update()\`, \`delete()\`, \`upsert()\`
- \`eq()\`, \`neq()\`, \`lt()\`, \`lte()\`, \`gt()\`, \`gte()\`, \`like()\`, \`ilike()\`, \`in()\`
- \`order()\`, \`limit()\`, \`range()\`
- Password auth, OTP, magic link (local only)
- Session management (cookies/memory)

## Partial Support (CLOSE/PARTIAL)

- RLS policies (basic role checks)
- Storage buckets (local filesystem)
- Realtime via EventBus (no WebSocket server)
- RPC calls (stub)

## Not Supported (UNSUPPORTED)

- Database webhooks
- Edge Functions (use Next.js API routes)
- Branching
- Real-time subscriptions over the network
- Postgres extensions (pgvector, etc.)

Run \`fakebase verify supabase\` for a live comparison.
`;

function generatePrompt(target: AiTarget): string {
  const base = `You are working on a Next.js project that uses Fakebase for local database development.

## Context

- Fakebase is a local-only, Supabase-shaped tool for prototyping
- Import the client: \`import { fakebase } from "@/lib/fakebase"\`
- Schema: \`fakebase/schema.ts\`
- Types: \`database.types.ts\` (auto-generated)
- Data stored in \`.fakebase/\` (gitignored, ephemeral)

## Rules

1. Never use \`@supabase/supabase-js\` — use the local Fakebase client
2. After schema changes: run \`fakebase migrate new && fakebase types gen\`
3. API is identical to Supabase's JavaScript client

## Example

\`\`\`ts
import { fakebase } from "@/lib/fakebase";
import type { Database } from "@/database.types";

type Profile = Database["public"]["Tables"]["profiles"]["Row"];

async function getProfile(userId: string): Promise<Profile | null> {
  const { data, error } = await fakebase
    .from("profiles")
    .select("*")
    .eq("user_id", userId)
    .single();
  if (error) throw error;
  return data;
}
\`\`\`
`;

  switch (target) {
    case "cursor":
      return `---
description: Task context for Cursor agent
---

${base}
`;
    case "claude":
      return `<system>
${base}
</system>
`;
    case "copilot":
      return `# GitHub Copilot Context\n\n${base}`;
    case "generic":
    default:
      return base;
  }
}

export async function runAiInit(cwd?: string): Promise<void> {
  const root = resolve(cwd ?? process.cwd());

  print.header("Fakebase AI Init");
  console.log();

  const files: Array<{ path: string; content: string; label: string }> = [
    {
      path: join(root, ".cursor", "rules", "fakebase.mdc"),
      content: FAKEBASE_MDC_CONTENT,
      label: ".cursor/rules/fakebase.mdc",
    },
    {
      path: join(root, "AGENTS.md"),
      content: AGENTS_MD_CONTENT,
      label: "AGENTS.md",
    },
    {
      path: join(root, "fakebase.rules.md"),
      content: FAKEBASE_RULES_MD_CONTENT,
      label: "fakebase.rules.md",
    },
    {
      path: join(root, "docs", "schema.summary.md"),
      content: SCHEMA_SUMMARY_CONTENT,
      label: "docs/schema.summary.md",
    },
    {
      path: join(root, "docs", "compatibility.summary.md"),
      content: COMPATIBILITY_SUMMARY_CONTENT,
      label: "docs/compatibility.summary.md",
    },
  ];

  for (const file of files) {
    const spinner = ora(`Writing ${file.label}…`).start();
    try {
      const dir = file.path.slice(0, file.path.lastIndexOf("/"));
      await mkdir(dir, { recursive: true });
      await writeFile(file.path, file.content, "utf8");
      spinner.succeed(`${file.label}`);
    } catch (err) {
      spinner.fail(
        `Failed to write ${file.label}: ${err instanceof Error ? err.message : String(err)}`,
      );
    }
  }

  console.log();
  print.success("AI rule files generated");
  print.step("Your AI agents now have full Fakebase context.");
}

export async function runAiPrompt(
  opts: { target?: string; output?: string },
  cwd?: string,
): Promise<void> {
  const target = (opts.target as AiTarget | undefined) ?? "generic";
  const prompt = generatePrompt(target);

  if (opts.output) {
    const outputPath = resolve(cwd ?? process.cwd(), opts.output);
    const dir = outputPath.slice(0, outputPath.lastIndexOf("/"));
    await mkdir(dir, { recursive: true });
    await writeFile(outputPath, prompt, "utf8");
    print.success(`Prompt written to ${opts.output}`);
  } else {
    process.stdout.write(prompt);
  }
}
