import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import ora from "ora";
import { loadConfig } from "../config.js";
import { loadSchemaIR } from "../runtime.js";
import { print } from "../ui/print.js";

export async function runTypesGen(cwd?: string): Promise<void> {
  const root = resolve(cwd ?? process.cwd());
  const config = await loadConfig(root);
  const outputPath = resolve(root, "database.types.ts");

  const spinner = ora("Generating TypeScript types from schema…").start();

  try {
    const schema = await loadSchemaIR(root, config);
    let typeContent: string;

    if (schema && schema.tables.length > 0) {
      const { generateTypes } = await import("@byronwade/types");
      typeContent = generateTypes(schema);
    } else {
      spinner.warn("No schema found — writing a starter database.types.ts");
      typeContent = generateFallbackTypes();
    }

    await writeFile(outputPath, typeContent, "utf8");
    spinner.succeed("Types generated");
    print.success("database.types.ts generated");
  } catch (err) {
    spinner.fail("Type generation failed");
    throw err;
  }
}

function generateFallbackTypes(): string {
  return [
    "// This file is auto-generated by `fakebase types gen`.",
    "// Do not edit manually.",
    "",
    "export type Json =",
    "  | string",
    "  | number",
    "  | boolean",
    "  | null",
    "  | { [key: string]: Json | undefined }",
    "  | Json[];",
    "",
    "export interface Database {",
    "  public: {",
    "    Tables: {",
    "      profiles: {",
    "        Row: {",
    "          id: string;",
    "          user_id: string;",
    "          username: string;",
    "          full_name: string | null;",
    "          avatar_url: string | null;",
    "          website: string | null;",
    "          updated_at: string | null;",
    "        };",
    "        Insert: {",
    "          id?: string;",
    "          user_id: string;",
    "          username: string;",
    "          full_name?: string | null;",
    "          avatar_url?: string | null;",
    "          website?: string | null;",
    "          updated_at?: string | null;",
    "        };",
    "        Update: Partial<Database['public']['Tables']['profiles']['Insert']>;",
    "      };",
    "    };",
    "    Views: Record<string, never>;",
    "    Functions: Record<string, never>;",
    "    Enums: Record<string, never>;",
    "  };",
    "}",
    "",
  ].join("\n");
}
