/**
 * Pure schema-IR → artifact generators for the playground Export panel. No
 * `node:` deps, so this is safe to import into client components. Mirrors what
 * `fakebase migrate export --supabase` and `fakebase types gen` produce, derived
 * live from `playgroundSchema`.
 */
import type { ProjectSchemaIR, TableIR, ColumnIR } from "@byronwade/fakebase";

/** Normalize the IR's short PG type names to Supabase SQL types. */
function sqlType(type: string): string {
  switch (type) {
    case "bool":
      return "boolean";
    case "int4":
      return "integer";
    case "int8":
      return "bigint";
    case "float8":
      return "double precision";
    default:
      return type; // uuid, text, timestamptz, jsonb, date… pass through
  }
}

function columnSql(col: ColumnIR): string {
  const parts: string[] = [`  ${col.name} ${sqlType(col.type)}`];
  if (col.primaryKey) parts.push("primary key");
  if (col.defaultSql) parts.push(`default ${col.defaultSql}`);
  if (col.nullable === false && !col.primaryKey) parts.push("not null");
  if (col.unique) parts.push("unique");
  if (col.references) {
    parts.push(`references ${col.references.table} (${col.references.column})`);
  }
  return parts.join(" ");
}

function tableSql(table: TableIR): string {
  const cols = table.columns.map(columnSql).join(",\n");
  const lines: string[] = [
    `create table ${table.schema}.${table.name} (`,
    cols,
    `);`,
  ];
  if (table.rlsEnabled) {
    lines.push(
      `alter table ${table.schema}.${table.name} enable row level security;`,
    );
  }
  for (const idx of table.indexes ?? []) {
    const unique = idx.unique ? "unique " : "";
    lines.push(
      `create ${unique}index ${idx.name} on ${table.schema}.${table.name} (${idx.columns.join(", ")});`,
    );
  }
  return lines.join("\n");
}

/** Supabase-compatible DDL for every table in the schema. */
export function schemaToSql(schema: ProjectSchemaIR): string {
  const header =
    "-- Generated by Fakebase · `fakebase migrate export --supabase`\n" +
    "-- Apply with: supabase db push (or paste into the SQL editor)\n";
  return header + "\n" + schema.tables.map(tableSql).join("\n\n") + "\n";
}

/** Map an IR column type to its TypeScript representation. */
function tsType(type: string): string {
  switch (type) {
    case "bool":
      return "boolean";
    case "int4":
    case "int8":
    case "float8":
    case "numeric":
      return "number";
    case "jsonb":
    case "json":
      return "Json";
    default:
      return "string"; // uuid, text, timestamptz, date…
  }
}

function fieldType(col: ColumnIR): string {
  const base = tsType(col.type);
  return col.nullable ? `${base} | null` : base;
}

/** True when a column may be omitted on insert (has a default, is nullable, or is the PK). */
function optionalOnInsert(col: ColumnIR): boolean {
  return Boolean(col.defaultSql) || col.nullable === true || col.primaryKey === true;
}

function tableType(table: TableIR): string {
  const row = table.columns
    .map((c) => `          ${c.name}: ${fieldType(c)};`)
    .join("\n");
  const insert = table.columns
    .map((c) => `          ${c.name}${optionalOnInsert(c) ? "?" : ""}: ${fieldType(c)};`)
    .join("\n");
  const update = table.columns
    .map((c) => `          ${c.name}?: ${fieldType(c)};`)
    .join("\n");
  return [
    `      ${table.name}: {`,
    `        Row: {`,
    row,
    `        };`,
    `        Insert: {`,
    insert,
    `        };`,
    `        Update: {`,
    update,
    `        };`,
    `      };`,
  ].join("\n");
}

/** A `database.types.ts`-shaped TypeScript string, mirroring `supabase gen types`. */
export function schemaToTypes(schema: ProjectSchemaIR): string {
  const tables = schema.tables.map(tableType).join("\n");
  return [
    "// Generated by Fakebase · `fakebase types gen`",
    "export type Json =",
    "  | string",
    "  | number",
    "  | boolean",
    "  | null",
    "  | { [key: string]: Json | undefined }",
    "  | Json[];",
    "",
    "export type Database = {",
    "  public: {",
    "    Tables: {",
    tables,
    "    };",
    "    Views: Record<never, never>;",
    "    Functions: Record<never, never>;",
    "  };",
    "};",
    "",
  ].join("\n");
}
