"use client";

import { useState } from "react";
import { Code2, RefreshCw, Download, Hash, Clock } from "lucide-react";
import { CodeBlock } from "@/components/CodeBlock";

// ---------------------------------------------------------------------------
// Fixture data
// ---------------------------------------------------------------------------

const TYPES_CONTENT = `// database.types.ts — Auto-generated by Fakebase
// Do not edit manually. Regenerate with: fakebase generate types
// Schema version: 42
// Generated: ${new Date().toISOString()}

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          role: string;
          created_at: string;
          email_confirmed: boolean;
        };
        Insert: {
          id?: string;
          email: string;
          role?: string;
          created_at?: string;
          email_confirmed?: boolean;
        };
        Update: {
          id?: string;
          email?: string;
          role?: string;
          created_at?: string;
          email_confirmed?: boolean;
        };
        Relationships: [];
      };
      posts: {
        Row: {
          id: string;
          title: string;
          body: string | null;
          published: boolean;
          author_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          body?: string | null;
          published?: boolean;
          author_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          body?: string | null;
          published?: boolean;
          author_id?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "posts_author_id_fkey";
            columns: ["author_id"];
            referencedRelation: "users";
            referencedColumns: ["id"];
          }
        ];
      };
      comments: {
        Row: {
          id: string;
          post_id: string;
          author_id: string;
          body: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          post_id: string;
          author_id: string;
          body: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          post_id?: string;
          author_id?: string;
          body?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "comments_post_id_fkey";
            columns: ["post_id"];
            referencedRelation: "posts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "comments_author_id_fkey";
            columns: ["author_id"];
            referencedRelation: "users";
            referencedColumns: ["id"];
          }
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      get_user_posts: {
        Args: { user_id: string };
        Returns: Database["public"]["Tables"]["posts"]["Row"][];
      };
    };
    Enums: {
      user_role: "admin" | "user" | "moderator";
    };
  };
}

export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];

export type InsertTables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];

export type UpdateTables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];

export type Enums<T extends keyof Database["public"]["Enums"]> =
  Database["public"]["Enums"][T];`;

const SCHEMA_HASH = "sha256:4a8f2c1d9e3b7f6a0c5d2e8b4a1f3c9d";
const LAST_GENERATED = new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString();

// ---------------------------------------------------------------------------
// Main page
// ---------------------------------------------------------------------------

export default function TypesPage() {
  const [typesContent, setTypesContent] = useState(TYPES_CONTENT);
  const [isRegenerating, setIsRegenerating] = useState(false);
  const [lastGenerated, setLastGenerated] = useState(LAST_GENERATED);

  async function handleRegenerate() {
    setIsRegenerating(true);
    // Simulate async regeneration
    await new Promise((r) => setTimeout(r, 800));
    setLastGenerated(new Date().toISOString());
    setTypesContent(
      TYPES_CONTENT.replace(/Generated: .+/, `Generated: ${new Date().toISOString()}`),
    );
    setIsRegenerating(false);
  }

  function handleDownload() {
    const blob = new Blob([typesContent], { type: "text/typescript" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "database.types.ts";
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="flex flex-col gap-0 h-full">
      {/* Header */}
      <div className="px-6 py-5 border-b border-gray-800 flex items-center justify-between flex-wrap gap-4">
        <div>
          <h1 className="text-lg font-semibold text-white">Types Viewer</h1>
          <p className="text-sm text-gray-500 mt-0.5">
            <span className="text-xs font-mono bg-yellow-500/10 text-yellow-400 px-1.5 py-0.5 rounded border border-yellow-500/20">
              DEV-ONLY
            </span>{" "}
            Generated TypeScript types for the Fakebase schema
          </p>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={handleRegenerate}
            disabled={isRegenerating}
            className="flex items-center gap-1.5 px-3 py-2 text-sm text-gray-400 hover:text-white bg-gray-800 border border-gray-700 rounded-lg transition-colors disabled:opacity-50"
          >
            <RefreshCw className={`h-4 w-4 ${isRegenerating ? "animate-spin" : ""}`} />
            Regenerate
          </button>
          <button
            onClick={handleDownload}
            className="flex items-center gap-1.5 px-3 py-2 text-sm text-white bg-blue-600 hover:bg-blue-700 rounded-lg transition-colors"
          >
            <Download className="h-4 w-4" />
            Download
          </button>
        </div>
      </div>

      {/* Metadata */}
      <div className="px-6 py-3 border-b border-gray-800 flex items-center gap-6 flex-wrap">
        <div className="flex items-center gap-2 text-xs text-gray-500">
          <Hash className="h-3.5 w-3.5" />
          <span className="font-mono">{SCHEMA_HASH}</span>
        </div>
        <div className="flex items-center gap-2 text-xs text-gray-500">
          <Clock className="h-3.5 w-3.5" />
          <span>Last generated: {new Date(lastGenerated).toLocaleString()}</span>
        </div>
        <div className="flex items-center gap-2 text-xs text-gray-500">
          <Code2 className="h-3.5 w-3.5" />
          <span>{typesContent.split("\n").length} lines</span>
        </div>
      </div>

      {/* Code preview */}
      <div className="flex-1 overflow-auto px-6 py-6">
        <CodeBlock code={typesContent} language="typescript" className="h-full" />
      </div>
    </div>
  );
}
