import { supabase } from "@/lib/fakebase";

export const dynamic = "force-dynamic";

export default async function Home() {
  // Two plain reads — no joins needed. The data was generated from the schema
  // by @fakebase/seed; there is no seed file in this project.
  const { data: posts, error } = await supabase
    .from("posts")
    .select("*")
    .order("created_at", { ascending: false });
  const { data: users } = await supabase.from("users").select("*");

  const authorById = new Map((users ?? []).map((u) => [u.id, u]));

  return (
    <main>
      <h1>Fake data, straight from the schema</h1>
      <p style={{ color: "var(--muted)" }}>
        This blog has <strong>{users?.length ?? 0} authors</strong> and{" "}
        <strong>{posts?.length ?? 0} posts</strong> — all generated by{" "}
        <code>@fakebase/seed</code> from <code>fakebase/schema.ts</code>. There is no
        seed file. Emails look like emails, every post has a real author, and the data
        is identical on every reload (deterministic seed).
      </p>

      {error && <p style={{ color: "#f87171" }}>Error: {error.message}</p>}

      {posts?.map((post) => {
        const author = authorById.get(post.author_id);
        return (
          <div className="note" key={post.id}>
            <span style={{ display: "flex", flexDirection: "column", gap: "0.2rem" }}>
              <strong>{post.title}</strong>
              <span style={{ color: "var(--muted)", fontSize: "0.85rem" }}>
                {post.excerpt}
              </span>
              <span style={{ color: "var(--muted)", fontSize: "0.8rem" }}>
                by {author ? `${author.first_name} ${author.last_name}` : "unknown"} ·{" "}
                {post.view_count} views · {post.published ? "published" : "draft"}
              </span>
            </span>
          </div>
        );
      })}
    </main>
  );
}
