/**
 * Rules generator for Fakebase — produces AI-readable rules, summaries,
 * and checklists describing the project schema and Fakebase constraints.
 */

import type {
  ProjectSchemaIR,
  TableIR,
  ColumnIR,
  PolicyIR,
  EnumIR,
} from "@fakebase/core";
import type { CapabilityEntry } from "@fakebase/core";
import { CapabilityStatus } from "@fakebase/core";

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

function mdTableRow(cells: string[]): string {
  return `| ${cells.join(" | ")} |`;
}

function mdTableHeader(headers: string[]): string {
  const separator = headers.map(() => "---").join(" | ");
  return [mdTableRow(headers), `| ${separator} |`].join("\n");
}

function renderColumnTable(columns: ColumnIR[]): string {
  const rows = columns.map((c) =>
    mdTableRow([
      `\`${c.name}\``,
      c.type,
      c.nullable ? "YES" : "NO",
      c.primaryKey
        ? "PK"
        : c.unique
          ? "UNIQUE"
          : c.references
            ? `FK → ${c.references.table}.${c.references.column}`
            : "",
      c.defaultSql ?? "",
    ]),
  );
  return [
    mdTableHeader(["Column", "Type", "Nullable", "Constraint", "Default"]),
    ...rows,
  ].join("\n");
}

function renderPoliciesForTable(table: TableIR): string {
  if (!table.rlsEnabled) return "_RLS disabled_";
  if (table.policies.length === 0)
    return "_RLS enabled — no policies defined (all access denied)_";
  return table.policies
    .map((p) => {
      const using = p.using ? `USING: \`${p.using}\`` : "";
      const check = p.withCheck ? `WITH CHECK: \`${p.withCheck}\`` : "";
      const expr = [using, check].filter(Boolean).join(" · ");
      return `- **${p.name}** (${p.command} · roles: ${p.roles.join(", ")}) ${expr ? `— ${expr}` : ""}`;
    })
    .join("\n");
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Generates `fakebase.rules.md` content — the primary AI rules file that
 * should be included in a project's `.cursor/rules/` or equivalent.
 */
export function generateFakebaseRules(
  schema: ProjectSchemaIR,
  options?: {
    projectName?: string;
    adapterType?: string;
  },
): string {
  const projectName = options?.projectName ?? "This project";
  const adapterType = options?.adapterType ?? "json";

  const tableRows = schema.tables
    .map((t) => {
      const cols = t.columns.map((c) => c.name).join(", ");
      const rlsStatus = t.rlsEnabled
        ? `✅ (${t.policies.length} policies)`
        : "❌ disabled";
      return mdTableRow([t.name, String(t.columns.length), cols, rlsStatus]);
    })
    .join("\n");

  const schemaTable = tableRows
    ? [mdTableHeader(["Table", "Columns", "Column Names", "RLS"]), tableRows].join("\n")
    : "_No tables defined_";

  const unsupportedList = [
    "- `auth.admin.*` — user management admin API",
    "- `storage.from().createSignedUploadUrl()` — signed upload URLs",
    "- `supabase.rpc()` with complex PL/pgSQL — only simple JS-evaluable expressions",
    "- Realtime broadcast to external subscribers",
    "- `pg_cron`, `pg_graphql`, `pg_net` extensions",
    "- Custom JWT claims beyond `role` and `sub`",
    "- Database webhooks and triggers",
    "- Edge Functions (use Next.js API routes instead)",
  ].join("\n");

  return `# Fakebase Rules

> Auto-generated by \`@fakebase/ai\`. Do not edit manually — regenerate with \`fakebase ai init\`.

## Project Overview

${projectName} uses **Fakebase** — a Supabase-shaped local development platform.
Fakebase runs entirely in-process using a \`${adapterType}\` adapter.
It is **not** a real Supabase project and must never be used in production.

Schema version: **${schema.version}** · Tables: **${schema.tables.length}** · Enums: **${schema.enums.length}** · Functions: **${schema.functions.length}**

---

## ⚠️ CRITICAL Warnings

> These constraints are hard rules. Violating them will cause incorrect behavior in production.

- **Fakebase is local/dev-only** — never treat it as production auth or RLS. All sessions, tokens, and users are ephemeral and stored only in memory or local JSON files.
- **RLS is approximate** — Fakebase evaluates policy expressions in JavaScript, not real PostgreSQL. Complex SQL expressions may not behave identically. Always verify against real Supabase before deploying.
- **Never invent unsupported APIs** — if a capability is not in the schema or returns \`CapabilityError.notImplemented()\`, do not attempt to use it or work around it. Surface the error clearly.
- **Always export Supabase SQL migrations** before claiming a backend feature is complete. Run \`fakebase export sql\` to produce migration files.
- **Run \`fakebase verify supabase\`** before production handoff to confirm schema compatibility.

---

## Schema Tables

${schemaTable}

---

## Client Usage

\`\`\`ts
import { createFakebaseClient } from "@fakebase/core";
import { JsonAdapter } from "@fakebase/adapter-${adapterType}";

const client = createFakebaseClient({
  adapter: new JsonAdapter({ dir: ".fakebase" }),
  schema: yourProjectSchema,
});

// Query
const { data, error } = await client.from("users").select("*");

// Insert
const { data, error } = await client.from("users").insert({ email: "test@example.com" });

// Auth
const { data: session } = await client.auth.signInWithPassword({
  email: "user@example.com",
  password: "password",
});
\`\`\`

---

## Migration Workflow

1. Develop against Fakebase locally using the \`json\` adapter
2. When schema is stable, run \`fakebase export sql > migrations/$(date +%s)_schema.sql\`
3. Review the generated SQL for correctness
4. Run \`fakebase generate types\` to produce \`database.types.ts\`
5. Run \`fakebase verify supabase\` to check compatibility
6. Apply migrations to your real Supabase project via the Supabase dashboard or CLI
7. Replace Fakebase client with \`@supabase/supabase-js\` in your app

---

## Unsupported Capabilities

The following APIs are not supported by Fakebase and will throw \`CapabilityError.notImplemented()\`:

${unsupportedList}

When asked to implement a feature using these APIs, explain that they are not supported
in the local dev environment and suggest a compatible alternative or deferred real-Supabase implementation.
`;
}

/**
 * Generates `schema.summary.md` — a human-readable description of all tables,
 * columns, relationships, enums, and RLS policies.
 */
export function generateSchemasSummary(schema: ProjectSchemaIR): string {
  const tablesSections = schema.tables
    .map((t) => {
      const fkRels = t.columns
        .filter((c) => c.references)
        .map(
          (c) =>
            `- \`${t.name}.${c.name}\` → \`${c.references!.table}.${c.references!.column}\``,
        )
        .join("\n");

      return [
        `### \`${t.name}\``,
        "",
        `Schema: \`${t.schema}\` · Primary key: \`${t.primaryKey}\` · RLS: ${t.rlsEnabled ? "✅ enabled" : "❌ disabled"}`,
        "",
        renderColumnTable(t.columns),
        "",
        fkRels ? `**Relationships:**\n${fkRels}` : "",
        "",
        t.indexes.length > 0
          ? `**Indexes:** ${t.indexes.map((i) => `\`${i.name}\` (${i.columns.join(", ")}${i.unique ? " UNIQUE" : ""})`).join(", ")}`
          : "",
        "",
        t.rlsEnabled ? `**Policies:**\n${renderPoliciesForTable(t)}` : "",
      ]
        .filter((line) => line !== undefined)
        .join("\n")
        .trim();
    })
    .join("\n\n---\n\n");

  const enumsSection =
    schema.enums.length === 0
      ? "_No enum types defined._"
      : schema.enums
          .map(
            (e: EnumIR) =>
              `### \`${e.name}\` (schema: \`${e.schema}\`)\n\nValues: ${e.values.map((v) => `\`${v}\``).join(", ")}`,
          )
          .join("\n\n");

  const functionsSection =
    schema.functions.length === 0
      ? "_No functions defined._"
      : schema.functions
          .map(
            (f) =>
              `### \`${f.name}\`\n\nArgs: ${f.args.length > 0 ? f.args.map((a) => `\`${a.name}: ${a.type}\``).join(", ") : "none"} → Returns: \`${f.returnType}\`${f.language ? ` (${f.language})` : ""}`,
          )
          .join("\n\n");

  return `# Schema Summary

> Auto-generated by \`@fakebase/ai\`. Schema version **${schema.version}**.

## Tables

${tablesSections || "_No tables defined._"}

---

## Enums

${enumsSection}

---

## Functions

${functionsSection}
`;
}

/**
 * Generates `policies.summary.md` — describes all RLS policies, role access,
 * and known limitations vs real Postgres RLS.
 */
export function generatePoliciesSummary(schema: ProjectSchemaIR): string {
  const tablesWithRls = schema.tables.filter((t) => t.rlsEnabled);
  const tablesWithoutRls = schema.tables.filter((t) => !t.rlsEnabled);

  const roleAccessMatrix = schema.tables.map((t) => {
    const policiesByRole: Record<string, string[]> = {};

    for (const policy of t.policies) {
      for (const role of policy.roles) {
        if (!policiesByRole[role]) policiesByRole[role] = [];
        policiesByRole[role].push(
          policy.command === "ALL" ? "SELECT/INSERT/UPDATE/DELETE" : policy.command,
        );
      }
    }

    const anon =
      policiesByRole["anon"]?.join(", ") ?? (t.rlsEnabled ? "—" : "ALL (no RLS)");
    const authenticated =
      policiesByRole["authenticated"]?.join(", ") ??
      (t.rlsEnabled ? "—" : "ALL (no RLS)");
    const serviceRole =
      policiesByRole["service_role"]?.join(", ") ?? "ALL (bypasses RLS)";

    return mdTableRow([`\`${t.name}\``, anon, authenticated, serviceRole]);
  });

  const accessMatrixTable =
    schema.tables.length > 0
      ? [
          mdTableHeader(["Table", "anon", "authenticated", "service_role"]),
          ...roleAccessMatrix,
        ].join("\n")
      : "_No tables defined._";

  const policySections = tablesWithRls
    .map((t) => {
      const policyDetails = t.policies
        .map((p: PolicyIR) => {
          const parts = [
            `**Policy:** \`${p.name}\``,
            `**Command:** ${p.command}`,
            `**Roles:** ${p.roles.join(", ")}`,
            `**Permissive:** ${p.permissive ? "YES" : "NO (restrictive)"}`,
          ];
          if (p.using) parts.push(`**USING:** \`${p.using}\``);
          if (p.withCheck) parts.push(`**WITH CHECK:** \`${p.withCheck}\``);
          return parts.join(" · ");
        })
        .map((line) => `- ${line}`)
        .join("\n");

      return `### \`${t.name}\`\n\n${policyDetails || "_No policies — all access denied._"}`;
    })
    .join("\n\n");

  const noRlsTables =
    tablesWithoutRls.length > 0
      ? tablesWithoutRls.map((t) => `- \`${t.name}\``).join("\n")
      : "_All tables have RLS enabled._";

  return `# RLS Policies Summary

> Auto-generated by \`@fakebase/ai\`. Schema version **${schema.version}**.

## ⚠️ Known Limitations vs Real Postgres RLS

- Fakebase evaluates \`USING\` and \`WITH CHECK\` expressions as JavaScript, not SQL
- Complex SQL functions (\`auth.uid()\`, \`auth.role()\`, \`current_setting()\`) are shimmed — behavior may differ
- Restrictive policies (\`AS RESTRICTIVE\`) interact with permissive policies; Fakebase approximates this
- RLS bypass for \`service_role\` is simulated by skipping policy evaluation entirely
- Always validate RLS behavior against a real Supabase project before deploying

---

## Role Access Matrix

${accessMatrixTable}

---

## Tables Without RLS

${noRlsTables}

---

## Policy Details by Table

${policySections || "_No RLS-enabled tables._"}
`;
}

/**
 * Generates `compatibility.summary.md` — a markdown table of all capabilities
 * and their support status.
 */
export function generateCompatibilitySummary(capabilities: CapabilityEntry[]): string {
  const sorted = [...capabilities].sort((a, b) => a.name.localeCompare(b.name));

  const statusEmoji: Record<CapabilityStatus, string> = {
    [CapabilityStatus.SUPPORTED]: "✅",
    [CapabilityStatus.PARTIAL]: "⚠️",
    [CapabilityStatus.STUB]: "🔶",
    [CapabilityStatus.UNSUPPORTED]: "❌",
  };

  const rows = sorted.map((c) =>
    mdTableRow([
      `\`${c.name}\``,
      `${statusEmoji[c.status as CapabilityStatus] ?? ""} ${c.status}`,
      c.notes ?? "",
      c.docsLink ? `[docs](${c.docsLink})` : "",
    ]),
  );

  const supported = sorted.filter(
    (c) => c.status === CapabilityStatus.SUPPORTED,
  ).length;
  const partial = sorted.filter((c) => c.status === CapabilityStatus.PARTIAL).length;
  const stub = sorted.filter((c) => c.status === CapabilityStatus.STUB).length;
  const unsupported = sorted.filter(
    (c) => c.status === CapabilityStatus.UNSUPPORTED,
  ).length;

  return `# Capability Compatibility Matrix

> Auto-generated by \`@fakebase/ai\`.

## Summary

| Status | Count |
| --- | --- |
| ✅ SUPPORTED | ${supported} |
| ⚠️ PARTIAL | ${partial} |
| 🔶 STUB | ${stub} |
| ❌ UNSUPPORTED | ${unsupported} |
| **Total** | **${sorted.length}** |

---

## All Capabilities

${[mdTableHeader(["Capability", "Status", "Notes", "Docs"]), ...rows].join("\n")}
`;
}

/**
 * Generates `migration.checklist.md` — a checklist of steps needed before
 * switching from Fakebase to real Supabase.
 */
export function generateMigrationChecklist(options?: {
  hasExportedSql?: boolean;
  hasGeneratedTypes?: boolean;
  hasRunVerify?: boolean;
  pendingMigrations?: string[];
}): string {
  const check = (done: boolean | undefined) => (done ? "[x]" : "[ ]");

  const hasPending = options?.pendingMigrations && options.pendingMigrations.length > 0;
  const pendingList = hasPending
    ? options!.pendingMigrations!.map((m) => `  - \`${m}\``).join("\n")
    : "";

  return `# Migration Checklist — Fakebase → Supabase

> Auto-generated by \`@fakebase/ai\`. Complete all items before switching to production Supabase.

## Pre-Migration Checklist

### Schema

- ${check(options?.hasExportedSql)} Export SQL migrations (\`fakebase export sql\`)
- ${check(!hasPending)} No pending unapplied migrations${hasPending ? `\n  Pending:\n${pendingList}` : ""}
- [ ] Review exported SQL for correctness and security
- [ ] Confirm all tables have appropriate RLS policies

### Types

- ${check(options?.hasGeneratedTypes)} Generate TypeScript types (\`fakebase generate types\`)
- [ ] Replace \`@fakebase/core\` client import with \`@supabase/supabase-js\`
- [ ] Update environment variables (SUPABASE_URL, SUPABASE_ANON_KEY)

### Verification

- ${check(options?.hasRunVerify)} Run \`fakebase verify supabase\`
- [ ] Test auth flows against real Supabase Auth
- [ ] Test RLS policies against real Supabase PostgreSQL
- [ ] Validate storage bucket configurations
- [ ] Test realtime subscriptions

### Production Handoff

- [ ] Remove Fakebase dependencies from \`package.json\`
- [ ] Remove \`.fakebase/\` directory from production builds
- [ ] Update CI/CD to use Supabase CLI (\`supabase db push\`)
- [ ] Document any known differences in behavior found during testing

---

## After Migration

Once migrated, the \`@fakebase/admin\` UI and all Fakebase-specific tooling should be removed
from the project. The Supabase Studio provides equivalent functionality.
`;
}
