"use client";

import { useState } from "react";
import { Sparkles, Copy, Check, Download, RefreshCw, ChevronDown } from "lucide-react";
import { CodeBlock } from "@/components/CodeBlock";

// ---------------------------------------------------------------------------
// Fixture data
// ---------------------------------------------------------------------------

const CAPABILITIES = [
  {
    name: "database.select",
    status: "SUPPORTED",
    notes: "Full eq/neq/in/like filters",
  },
  { name: "database.insert", status: "SUPPORTED", notes: "Single and batch inserts" },
  { name: "database.update", status: "SUPPORTED", notes: "With filters" },
  { name: "database.delete", status: "SUPPORTED", notes: "With filters" },
  { name: "database.upsert", status: "SUPPORTED", notes: "On conflict do update" },
  {
    name: "database.rpc",
    status: "PARTIAL",
    notes: "Simple JS-evaluable expressions only",
  },
  {
    name: "database.joins",
    status: "PARTIAL",
    notes: "Embedded selects, no explicit JOINs",
  },
  {
    name: "database.full_text_search",
    status: "STUB",
    notes: "Returns CapabilityError",
  },
  {
    name: "auth.signInWithPassword",
    status: "SUPPORTED",
    notes: "In-memory password store",
  },
  {
    name: "auth.signInWithOtp",
    status: "SUPPORTED",
    notes: "OTP stored in memory inbox",
  },
  { name: "auth.signInWithOAuth", status: "STUB", notes: "Returns CapabilityError" },
  {
    name: "auth.admin.listUsers",
    status: "SUPPORTED",
    notes: "Returns all local users",
  },
  {
    name: "auth.admin.createUser",
    status: "SUPPORTED",
    notes: "Creates in-memory user",
  },
  {
    name: "auth.admin.deleteUser",
    status: "SUPPORTED",
    notes: "Removes from in-memory store",
  },
  { name: "auth.mfa", status: "UNSUPPORTED", notes: "Multi-factor auth not available" },
  {
    name: "storage.upload",
    status: "SUPPORTED",
    notes: "Writes to local .fakebase/storage/",
  },
  {
    name: "storage.download",
    status: "SUPPORTED",
    notes: "Reads from local .fakebase/storage/",
  },
  { name: "storage.signedUrls", status: "STUB", notes: "Returns CapabilityError" },
  {
    name: "storage.transformations",
    status: "UNSUPPORTED",
    notes: "Image transformations not available",
  },
  { name: "realtime.channel", status: "SUPPORTED", notes: "In-process pub/sub" },
  {
    name: "realtime.postgres_changes",
    status: "SUPPORTED",
    notes: "Emits local change events",
  },
  {
    name: "realtime.broadcast",
    status: "PARTIAL",
    notes: "In-process only, no external subscribers",
  },
  { name: "realtime.presence", status: "PARTIAL", notes: "In-process only" },
];

type Status = "SUPPORTED" | "PARTIAL" | "STUB" | "UNSUPPORTED";

const STATUS_STYLES: Record<Status, string> = {
  SUPPORTED: "text-green-400  bg-green-500/10  border-green-500/20",
  PARTIAL: "text-yellow-400 bg-yellow-500/10 border-yellow-500/20",
  STUB: "text-orange-400 bg-orange-500/10 border-orange-500/20",
  UNSUPPORTED: "text-red-400    bg-red-500/10    border-red-500/20",
};

type PromptTarget = "cursor" | "claude" | "copilot" | "generic";

const RULES_CONTENT = `# Fakebase Rules

> Auto-generated by \`@fakebase/ai\`.

## Project Overview

This project uses **Fakebase** — a Supabase-shaped local development platform.
It is **not** a real Supabase project and must never be used in production.

Schema version: **42** · Tables: **3** · Enums: **1** · Functions: **1**

---

## ⚠️ CRITICAL Warnings

- **Fakebase is local/dev-only** — never treat it as production auth or RLS
- **RLS is approximate** — policy expressions are evaluated in JavaScript, not real PostgreSQL
- **Never invent unsupported APIs** — return \`CapabilityError.notImplemented()\`
- **Always export Supabase SQL migrations** before claiming a backend feature is complete
- **Run \`fakebase verify supabase\`** before production handoff

---

## Schema Tables

| Table | Columns | RLS |
| --- | --- | --- |
| users | id, email, role, created_at, email_confirmed | ✅ (3 policies) |
| posts | id, title, body, published, author_id, created_at | ✅ (3 policies) |
| comments | id, post_id, author_id, body, created_at | ❌ disabled |

---

## Client Usage

\`\`\`ts
import { createFakebaseClient } from "@fakebase/core";
import { JsonAdapter } from "@fakebase/adapter-json";

const client = createFakebaseClient({
  adapter: new JsonAdapter({ dir: ".fakebase" }),
  schema: projectSchema,
});
\`\`\`

---

## Migration Workflow

1. Run \`fakebase export sql\`
2. Review and commit the migration file
3. Run \`fakebase generate types\`
4. Run \`fakebase verify supabase\`
`;

const PROMPT_BY_TARGET: Record<PromptTarget, string> = {
  cursor: `---
description: Fakebase local dev rules — schema v42
globs: ["**/*.ts", "**/*.tsx"]
alwaysApply: true
---

# Fakebase Local Dev Rules

This project uses Fakebase (local Supabase-shaped runtime). **Not production.**

## Schema Tables

- **users** (id:uuid, email:text, role:text) — RLS: enabled
- **posts** (id:uuid, title:text, author_id:uuid) — RLS: enabled
- **comments** (id:uuid, body:text) — RLS: disabled

## Rules

1. NEVER treat Fakebase as production Supabase
2. NEVER invent unsupported APIs
3. Always note RLS is approximate
4. Always run \`fakebase export sql\` before claiming complete`,

  claude: `<system>
<context>
This project uses Fakebase — a local-only Supabase-shaped runtime. Schema v42.
NOT production Supabase. Auth, RLS, and storage are approximations.
</context>
<schema>
- users (id:uuid, email:text, role:text) — RLS enabled
- posts (id:uuid, title:text, author_id:uuid) — RLS enabled
- comments (id:uuid, body:text) — RLS disabled
</schema>
<guidelines>
1. Local dev only — never production
2. Never invent unsupported APIs
3. RLS is approximate JS evaluation
4. Always export SQL before claiming complete
</guidelines>
</system>`,

  copilot: `# Fakebase Development Context

This project uses Fakebase (local Supabase-shaped runtime, schema v42).
NOT production Supabase.

## Database Schema

- **users** (id:uuid, email:text, role:text) — RLS enabled
- **posts** (id:uuid, title:text, author_id:uuid) — RLS enabled
- **comments** (id:uuid, body:text) — RLS disabled

## Rules

1. Local dev only — never production
2. Never invent unsupported APIs — CapabilityError.notImplemented()
3. RLS is approximate JavaScript evaluation
4. Always fakebase export sql before completion`,

  generic: `# Fakebase Project Context

Fakebase is a local-only Supabase-shaped development platform.
NOT production Supabase. Schema version 42.

## Database Schema

- users (id:uuid, email:text, role:text) — RLS enabled
- posts (id:uuid, title:text, author_id:uuid) — RLS enabled
- comments (id:uuid, body:text) — RLS disabled

## Core Rules

1. Local dev only — never production
2. Never invent unsupported APIs
3. RLS is approximate
4. Always export SQL before completion`,
};

// ---------------------------------------------------------------------------
// Main page
// ---------------------------------------------------------------------------

export default function AIPage() {
  const [promptTarget, setPromptTarget] = useState<PromptTarget>("cursor");
  const [isGenerating, setIsGenerating] = useState(false);
  const [copiedPrompt, setCopiedPrompt] = useState(false);
  const [showRules, setShowRules] = useState(false);
  const [statusFilter, setStatusFilter] = useState<Status | "ALL">("ALL");

  const filteredCapabilities =
    statusFilter === "ALL"
      ? CAPABILITIES
      : CAPABILITIES.filter((c) => c.status === statusFilter);

  const counts: Record<Status, number> = {
    SUPPORTED: CAPABILITIES.filter((c) => c.status === "SUPPORTED").length,
    PARTIAL: CAPABILITIES.filter((c) => c.status === "PARTIAL").length,
    STUB: CAPABILITIES.filter((c) => c.status === "STUB").length,
    UNSUPPORTED: CAPABILITIES.filter((c) => c.status === "UNSUPPORTED").length,
  };

  async function handleCopyPrompt() {
    await navigator.clipboard.writeText(PROMPT_BY_TARGET[promptTarget]);
    setCopiedPrompt(true);
    setTimeout(() => setCopiedPrompt(false), 2000);
  }

  async function handleGenerateRules() {
    setIsGenerating(true);
    await new Promise((r) => setTimeout(r, 600));
    setIsGenerating(false);
    setShowRules(true);
  }

  function handleDownloadRules() {
    const blob = new Blob([RULES_CONTENT], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "fakebase.rules.md";
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="flex flex-col gap-0">
      {/* Header */}
      <div className="px-6 py-5 border-b border-gray-800 flex items-center justify-between">
        <div>
          <h1 className="text-lg font-semibold text-white flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-blue-400" />
            AI Tools
          </h1>
          <p className="text-sm text-gray-500 mt-0.5">
            <span className="text-xs font-mono bg-yellow-500/10 text-yellow-400 px-1.5 py-0.5 rounded border border-yellow-500/20">
              DEV-ONLY
            </span>{" "}
            Generate rules files, prompts, and compatibility reports for AI agents
          </p>
        </div>
      </div>

      <div className="px-6 py-6 space-y-10">
        {/* Capability matrix */}
        <section>
          <div className="flex items-center justify-between mb-4 flex-wrap gap-3">
            <h2 className="text-sm font-semibold text-gray-300">Capability Matrix</h2>
            <div className="flex items-center gap-2 flex-wrap">
              {(["ALL", "SUPPORTED", "PARTIAL", "STUB", "UNSUPPORTED"] as const).map(
                (s) => (
                  <button
                    key={s}
                    onClick={() => setStatusFilter(s)}
                    className={`text-xs px-2.5 py-1 rounded-full border transition-colors ${statusFilter === s ? "bg-gray-700 text-white border-gray-600" : "text-gray-500 border-gray-700 hover:text-gray-300"}`}
                  >
                    {s === "ALL"
                      ? `All (${CAPABILITIES.length})`
                      : `${s} (${counts[s]})`}
                  </button>
                ),
              )}
            </div>
          </div>

          {/* Summary pills */}
          <div className="flex items-center gap-3 mb-4 flex-wrap">
            {(Object.entries(counts) as [Status, number][]).map(([status, count]) => (
              <div
                key={status}
                className={`flex items-center gap-1.5 text-xs px-3 py-1.5 rounded-full border ${STATUS_STYLES[status]}`}
              >
                <span className="font-semibold">{count}</span>
                <span>{status}</span>
              </div>
            ))}
          </div>

          <div className="overflow-x-auto rounded-lg border border-gray-800">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-gray-800 bg-gray-900">
                  <th className="px-4 py-3 text-left font-medium text-gray-400">
                    Capability
                  </th>
                  <th className="px-4 py-3 text-left font-medium text-gray-400">
                    Status
                  </th>
                  <th className="px-4 py-3 text-left font-medium text-gray-400">
                    Notes
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-800">
                {filteredCapabilities.map((cap) => (
                  <tr key={cap.name} className="hover:bg-gray-800/40">
                    <td className="px-4 py-3 font-mono text-xs text-gray-300">
                      {cap.name}
                    </td>
                    <td className="px-4 py-3">
                      <span
                        className={`text-xs px-2 py-0.5 rounded border font-medium ${STATUS_STYLES[cap.status as Status]}`}
                      >
                        {cap.status}
                      </span>
                    </td>
                    <td className="px-4 py-3 text-xs text-gray-500">{cap.notes}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        {/* Generate rules */}
        <section>
          <h2 className="text-sm font-semibold text-gray-300 mb-4">
            Generate Rules Files
          </h2>
          <div className="bg-gray-900 border border-gray-800 rounded-lg p-4">
            <p className="text-sm text-gray-400 mb-4">
              Generate AI rules files based on the current schema. This is equivalent to
              running{" "}
              <code className="text-blue-400 bg-gray-800 px-1.5 py-0.5 rounded font-mono text-xs">
                fakebase ai init
              </code>
              .
            </p>
            <div className="flex items-center gap-3">
              <button
                onClick={handleGenerateRules}
                disabled={isGenerating}
                className="flex items-center gap-1.5 px-4 py-2 bg-blue-600 hover:bg-blue-700 disabled:opacity-50 text-white text-sm rounded-lg transition-colors"
              >
                <RefreshCw
                  className={`h-4 w-4 ${isGenerating ? "animate-spin" : ""}`}
                />
                {isGenerating ? "Generating..." : "Generate Rules Files"}
              </button>
              {showRules && (
                <button
                  onClick={handleDownloadRules}
                  className="flex items-center gap-1.5 px-3 py-2 text-sm text-gray-400 hover:text-white bg-gray-800 border border-gray-700 rounded-lg transition-colors"
                >
                  <Download className="h-4 w-4" />
                  Download fakebase.rules.md
                </button>
              )}
            </div>
            {showRules && (
              <div className="mt-4">
                <CodeBlock code={RULES_CONTENT} language="markdown" />
              </div>
            )}
          </div>
        </section>

        {/* Prompt generator */}
        <section>
          <h2 className="text-sm font-semibold text-gray-300 mb-4">
            Agent Prompt Generator
          </h2>
          <div className="bg-gray-900 border border-gray-800 rounded-lg p-4 space-y-4">
            <div className="flex items-center gap-4">
              <label className="text-sm text-gray-400">Target:</label>
              <div className="relative">
                <select
                  value={promptTarget}
                  onChange={(e) => setPromptTarget(e.target.value as PromptTarget)}
                  className="appearance-none bg-gray-800 border border-gray-700 rounded-lg pl-3 pr-8 py-2 text-sm text-white focus:outline-none focus:border-blue-500"
                >
                  <option value="cursor">Cursor (.cursor/rules/)</option>
                  <option value="claude">Claude (CLAUDE.md)</option>
                  <option value="copilot">
                    GitHub Copilot (.github/copilot-instructions.md)
                  </option>
                  <option value="generic">Generic (AGENTS.md)</option>
                </select>
                <ChevronDown className="pointer-events-none absolute right-2.5 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-400" />
              </div>
              <button
                onClick={handleCopyPrompt}
                className="flex items-center gap-1.5 ml-auto px-3 py-2 text-sm text-gray-400 hover:text-white bg-gray-800 border border-gray-700 rounded-lg transition-colors"
              >
                {copiedPrompt ? (
                  <>
                    <Check className="h-4 w-4 text-green-400" />
                    <span className="text-green-400">Copied!</span>
                  </>
                ) : (
                  <>
                    <Copy className="h-4 w-4" />
                    Copy Prompt
                  </>
                )}
              </button>
            </div>
            <CodeBlock
              code={PROMPT_BY_TARGET[promptTarget]}
              language={
                promptTarget === "cursor"
                  ? "markdown"
                  : promptTarget === "claude"
                    ? "xml"
                    : "markdown"
              }
            />
          </div>
        </section>
      </div>
    </div>
  );
}
